In [291]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

data = pd.read_csv(r'F:\Github_dsc\HousePrice_MegaProject\1. data_gathering\3. merging data\cx_data\1. manually cleaned data\independent-house - independent-house.csv')
data.sample(3)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
154,4 Bedroom House for sale in Sector 109 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,International City by Sobha Phase 1,6.3 Crore,"₹ 9,000/sq.ft.",(650 sq.m.) Built-up Area,Built Up area: 7000 (650.32 sq.m.)Carpet area:...,4 Bedrooms,5 Bathrooms,3+ Balconies,NaN,"Hn Number, Sector 109 Gurgaon, Gurgaon, Haryana",2 Floors,West,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",Sobha international city sector 109 gurgaon \n...,"['9 Fan', '1 Geyser', '27 Light', '8 AC', '1 C...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",R70071386
505,9 Bedroom House for sale in Rattan Garden,https://www.99acres.com/9-bhk-bedroom-independ...,Rattan Garden,1.1 Crore,"₹ 8,730/sq.ft.",(117 sq.m.) Plot Area,Plot area 140(117.06 sq.m.),9 Bedrooms,3 Bathrooms,3 Balconies,NaN,"431, Rattan Garden, Gurgaon, Haryana",3 Floors,NaN,10+ Year Old,"['Chintapurni Mandir', 'Ravi Clinic and Health...",Old construction.....Ready to live - 9 rooms ....,NaN,['Visitor Parking'],"['Environment3 out of 5', 'Lifestyle4 out of 5...",M68298578
960,3 Bedroom House for sale in Nirvana Country,https://www.99acres.com/3-bhk-bedroom-independ...,Unitech Nirvana Birch Court,7.1 Crore,"₹ 283,333/sq.ft.",(22 sq.m.) Plot Area,Plot area 240(22.3 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"Nirvana Country, Gurgaon, Haryana",1 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",It is good livable house with 100 power backup...,"['1 Modular Kitchen', '3 Wardrobe', 'No AC', '...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ...",D61488894

In [292]:
data.drop(columns=['link', 'property_id'], inplace=True)

In [293]:
data.sample(3)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
582,4 Bedroom House for sale in Sector 103 Gurgaon,Satya The Hermitage3.5 ★,3.15 Crore,"₹ 6,702/sq.ft.",(437 sq.m.) Built-up Area,Built Up area: 4700 (436.64 sq.m.),4 Bedrooms,5 Bathrooms,No Balcony,NaN,"Sector 103, Sector 103 Gurgaon, Gurgaon, Haryana",12 Floors,East,undefined,"['Metro Hospital, Palam Vihar', 'Huda Metro St...",4bhk penthouse for resale in satya the hermita...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1011,4 Bedroom House for sale in DLF Phase 3,NaN,6.5 Crore,"₹ 22,855/sq.ft.",(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Pooja Room,"DLF Phase 3, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Old built up plot rate gated complex\nNearest ...,"['4 Wardrobe', '6 Fan', '12 Light', '1 Modular...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
424,4 Bedroom House for sale in Arjun Nagar,NaN,82 Lac,"₹ 10,224/sq.ft.",(75 sq.m.) Carpet Area,Carpet area: 802 (74.51 sq.m.),4 Bedrooms,4 Bathrooms,No Balcony,NaN,"Arjun Nagar, Gurgaon, Haryana, India, Arjun Na...",2 Floors,NaN,undefined,"['Lal Superspeciality Hospital', 'Shri Gobind ...",An independant 2 storey well maintained house ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

# society col

In [294]:
data['society'].value_counts(dropna=False)

society
NaN                                                  624
Vipul Tatvam Villa                                    27
Emaar MGF Marbella                                    26
International City by SOBHA Phase 2                   26
International City by Sobha Phase 1                   23
Unitech Uniworld Resorts                              14
DLF City Plots                                        11
DLF City Plots Phase 2                                11
Unitech Espace                                        11
Bptp Visionnaire                                       9
Eldeco Mansionz                                        9
Uppal Southend4.0 ★                                    9
Not Applicable                                         7
Experion Windchants3.8 ★                               6
Ansals Palam Vihar                                     6
Sushant Lok 1 Builder Floors                           6
DLF New Town Heights 24.0 ★                            5
DLF City Phase 1                                       5
Vatika India Next4.1 ★                                 4
Unitech Nirvana Birch Court                            4
Ansal Sushant Lok Plots4.1 ★                           4
nul                                                    4
Ansals Florence Villa                                  4
Unitech Aspen Greens                                   4
DLF Alameda                                            4
Vatika Signature Villas                                3
Eros Rosewood City4.0 ★                                3
Sector 14 RWA                                          3
Eros Rosewood Villas                                   3
Palam Vihar Extension West Zone RWA                    3
Malibu Towne                                           3
Housing Board Colony                                   3
BPTP Astaire Gardens3.7 ★                              3
Rattan Garden                                          3
Hans Enclave                                           3
HUDA Ashok Vihar Phase 13.9 ★                          3
Bestech Park View Ananda4.2 ★                          3
SS Aaron Ville                                         3
Silverglades Tarudhan Valley Golf Resort               3
Tata Primanti4.1 ★                                     3
Puri Diplomatic Greens4.0 ★                            3
Luxury DLF City Floors                                 3
Central Park Flower Valley                             3
DLF City Plots Phase 3                                 3
Anant Raj Estates                                      3
Suncity Township4.1 ★                                  2
IFFCO Nagar and 17B RWA                                2
Bhim Garh Kheri                                        2
Sobha City                                             2
DLF South City 1                                       2
Ansal Sushant Residency                                2
Ardee City3.8 ★                                        2
DLF New Town Heights3.7 ★                              2
Signature Global City 92                               2
Satya The Hermitage3.5 ★                               2
Unitech Deerwood Chase                                 2
Suncity Essel Towers4.2 ★                              2
Emaar The Palm Springs                                 2
Project Mianwali Colony                                2
Nirvana Cedar Crest                                    2
Ansal API Esencia3.7 ★                                 2
SS Hibiscus                                            2
Saksham Welfare Association                            2
Unitech Palms South City 1                             2
BPTP Pedestal                                          2
RWA Sector 46                                          2
Sector 38 RWA                                          2
Project Housing Board Colony                           2
Unitech Escape3.8 ★                                    2
DLF City Plots Phase 4                                 2
Emaar Emerald Hills4.1 ★                               2
shivpuri                                               2
Spaze Privy3.9 ★                                       2
Om Nagar, Sector-11                                    1
Ireo Victory Valley4.1 ★                               1
Grover Homes Sec 4                                     1
4S Aradhya Homes                                       1
Ansal API Spanish Court                                1
secter 16a daultabad faridabad house no 313            1
Central Park Flower Valley Cerise Floors               1
FLOOR WISE DESIGNER KOTHI                              1
Birla Navya                                            1
Kothi                                                  1
rajendra park sec 105                                  1
nirvana country                                        1
Smart World Orchard                                    1
Landmark House                                         1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
Sector 15 Part 2 RWA                                   1
Nitin Vihar                                            1
Ansal                                                  1
Ashok vihar phase III Extension                        1
Ansal Heights3.2 ★                                     1
rattan vihar rajendra park                             1
Signature Global City 63A                              1
DLF City Plot Phase 3                                  1
Adani Brahma Samsara4.2 ★                              1
Ansal Florence Super                                   1
Unitech South City 23.8 ★                              1
Sheetla Enclave                                        1
patel nager house no 927/5                             1
Huda Floor                                             1
Huda                                                   1
Anant Raj Manor Villas                                 1
Sector 57 Huda                                         1
Godrej Meridien                                        1
Ansal Sushant Lok 2                                    1
The Laburnum                                           1
Vatika Independent Floors3.8 ★                         1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road      1
Sector-17C                                             1
DLF Pink Town House4.0 ★                               1
huda sector-56 gurgaon                                 1
Satya The Legend3.8 ★                                  1
Prem Kunj                                              1
Ireo Victory Valley4.0 ★                               1
Independent House Sector 45                            1
Ashok Vihar Phase 3 Gurgaon                            1
Farrukhnagar                                           1
Unitech Greenwood City3.6 ★                            1
Vatika The Seven Lamps3.8 ★                            1
Nirvana Country                                        1
Ansal Sushant Lok                                      1
Central Park                                           1
Signature Global City 81                               1
Signature Global City                                  1
DLF Floors Phase 3                                     1
sneh vihar                                             1
Suncity Avenue 76                                      1
DLF The Arbour                                         1
Surendra Homes Dayanand Colony                         1
Laxmi Garden Sector-11                                 1
HUDA Housing Board Colony4.1 ★                         1
DLF Gardencity Enclave                                 1
shree krishna homes                                    1
Smart World Gems                                       1
Ganpati Heights Apartment                              1
Hero Homes                                             1
Jacobpura Gurugram                                     1
Anand Garden, Sector-105                               1
Rajendra Park Gurgaon                                  1
RK Excelo                                              1
DLF The Grove                                          1
house number B-34                                      1
Shri Shyam Residency                                   1
ATS Tourmaline3.9 ★                                    1
Bhawani enclave                                        1
Vatika Sovereign Next                                  1
MANOHAR NAGAR                                          1
Laxman vihar phase 2                                   1
Anamika Enclave                                        1
bhim nagar, sector 6                                   1
Emaar MGF The Palm Drive4.1 ★                          1
All Punjabi Welfare Association                        1
Tulip Ivory3.5 ★                                       1
Huda Plots                                             1
DLF Garden City Floors                                 1
Ansal Celebrity Homes                                  1
mian wali                                              1
SS Omnia                                               1
Bhim Nagar Society                                     1
Anshul                                                 1
Sare Crescent Parc Royal Greens Phase 1                1
Ninex City                                             1
Vipul World3.9 ★                                       1
Greenopolis                                            1
Ansal Esencia Sovereign Floors                         1
Nirmal Enclave, Maruti Kunj Road                       1
jacob pura                                             1
mahavir pura                                           1
Raj Villas                                             1
sector 37                                              1
Shivaji Nagar Residential                              1
private house                                          1
Surat nagar phase 2                                    1
DLF City Plot Phase 4                                  1
Sai Kripa Floors 5                                     1
Naman Residency                                        1
Krishna Palace                                         1
Signature Global Park4.0 ★                             1
Huda Flats                                             1
Jacobpura                                              1
Indiabulls Centrum Park3.7 ★                           1
Madan puri                                             1
My Home                                                1
ROW HOUSE                                              1
HUDA Plot Sector 38                                    1
Tulip Yellow                                           1
Name: count, dtype: int64

In [295]:
import regex as re
data['society'].str.lower().str.strip().astype(str).apply(lambda row: re.sub(r'\d+(\.\d+)?\s?★', '', row)).value_counts(dropna=False)

society
nan                                                  624
vipul tatvam villa                                    27
emaar mgf marbella                                    26
international city by sobha phase 2                   26
international city by sobha phase 1                   23
unitech uniworld resorts                              14
dlf city plots                                        11
dlf city plots phase 2                                11
unitech espace                                        11
bptp visionnaire                                       9
eldeco mansionz                                        9
uppal southend                                         9
not applicable                                         7
experion windchants                                    6
ansals palam vihar                                     6
sushant lok 1 builder floors                           6
dlf new town heights                                   5
dlf city phase 1                                       5
vatika india next                                      4
unitech nirvana birch court                            4
ansal sushant lok plots                                4
nul                                                    4
ansals florence villa                                  4
unitech aspen greens                                   4
dlf alameda                                            4
vatika signature villas                                3
eros rosewood city                                     3
sector 14 rwa                                          3
eros rosewood villas                                   3
palam vihar extension west zone rwa                    3
malibu towne                                           3
housing board colony                                   3
bptp astaire gardens                                   3
rattan garden                                          3
hans enclave                                           3
huda ashok vihar phase                                 3
bestech park view ananda                               3
ss aaron ville                                         3
silverglades tarudhan valley golf resort               3
puri diplomatic greens                                 3
central park flower valley                             3
tata primanti                                          3
anant raj estates                                      3
dlf city plots phase 3                                 3
luxury dlf city floors                                 3
sobha city                                             2
dlf south city 1                                       2
suncity essel towers                                   2
ansal sushant residency                                2
ardee city                                             2
dlf new town heights                                   2
unitech escape                                         2
bhim garh kheri                                        2
iffco nagar and 17b rwa                                2
satya the hermitage                                    2
suncity township                                       2
unitech deerwood chase                                 2
nirvana country                                        2
emaar the palm springs                                 2
project housing board colony                           2
ansal api esencia                                      2
ireo victory valley                                    2
ss hibiscus                                            2
saksham welfare association                            2
unitech palms south city 1                             2
bptp pedestal                                          2
rwa sector 46                                          2
sector 38 rwa                                          2
nirvana cedar crest                                    2
signature global city 92                               2
emaar emerald hills                                    2
spaze privy                                            2
project mianwali colony                                2
shivpuri                                               2
dlf city plots phase 4                                 2
dlf the arbour                                         1
landmark house                                         1
grover homes sec 4                                     1
4s aradhya homes                                       1
ansal api spanish court                                1
central park flower valley cerise floors               1
floor wise designer kothi                              1
birla navya                                            1
kothi                                                  1
rajendra park sec 105                                  1
ansal heights                                          1
ninex city                                             1
ansal florence super                                   1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
sector 15 part 2 rwa                                   1
nitin vihar                                            1
ansal                                                  1
ashok vihar phase iii extension                        1
rattan vihar rajendra park                             1
signature global city 63a                              1
dlf city plot phase 3                                  1
adani brahma samsara                                   1
sneh vihar                                             1
secter 16a daultabad faridabad house no 313            1
unitech south city                                     1
smart world orchard                                    1
suncity avenue 76                                      1
huda floor                                             1
huda                                                   1
anant raj manor villas                                 1
sector 57 huda                                         1
godrej meridien                                        1
ansal sushant lok 2                                    1
the laburnum                                           1
vatika independent floors                              1
arjun marg/ sector- 26 phase- 1/ golf course road      1
sector-17c                                             1
dlf pink town house                                    1
huda sector-56 gurgaon                                 1
patel nager house no 927/5                             1
satya the legend                                       1
independent house sector 45                            1
ashok vihar phase 3 gurgaon                            1
farrukhnagar                                           1
unitech greenwood city                                 1
vatika the seven lamps                                 1
ansal sushant lok                                      1
central park                                           1
signature global city 81                               1
signature global city                                  1
dlf floors phase 3                                     1
prem kunj                                              1
sheetla enclave                                        1
ss omnia                                               1
dlf garden city floors                                 1
mian wali                                              1
ansal celebrity homes                                  1
laxmi garden sector-11                                 1
huda housing board colony                              1
tulip yellow                                           1
house number b-34                                      1
smart world gems                                       1
ganpati heights apartment                              1
hero homes                                             1
jacobpura gurugram                                     1
anand garden, sector-105                               1
ats tourmaline                                         1
rk excelo                                              1
dlf the grove                                          1
surendra homes dayanand colony                         1
bhawani enclave                                        1
om nagar, sector-11                                    1
vatika sovereign next                                  1
manohar nagar                                          1
laxman vihar phase 2                                   1
anamika enclave                                        1
bhim nagar, sector 6                                   1
emaar mgf the palm drive                               1
all punjabi welfare association                        1
tulip ivory                                            1
huda plots                                             1
shri shyam residency                                   1
rajendra park gurgaon                                  1
anshul                                                 1
huda plot sector 38                                    1
sare crescent parc royal greens phase 1                1
signature global park                                  1
vipul world                                            1
greenopolis                                            1
ansal esencia sovereign floors                         1
nirmal enclave, maruti kunj road                       1
jacob pura                                             1
mahavir pura                                           1
raj villas                                             1
sector 37                                              1
shivaji nagar residential                              1
bhim nagar society                                     1
my home                                                1
private house                                          1
dlf city plot phase 4                                  1
sai kripa floors 5                                     1
naman residency                                        1
krishna palace                                         1
surat nagar phase 2                                    1
huda flats                                             1
jacobpura                                              1
indiabulls centrum park                                1
madan puri                                             1
dlf gardencity enclave                                 1
row house                                              1
shree krishna homes                                    1
Name: count, dtype: int64

In [296]:
data['society'] = data['society'].str.lower().str.strip().astype(str).apply(lambda row: re.sub(r'\d+(\.\d+)?\s?★', '', row))

In [297]:
data.sample(3)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
568,1 Bedroom House for sale in Sector 39 Gurgaon,nan,1.8 Crore,"₹ 21,875/sq.ft.",(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.)Built Up area: 800 s...,1 Bedroom,1 Bathroom,2 Balconies,NaN,"00., Sector 39 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",1bhk residential house for resale in sector 39...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
212,4 Bedroom House for sale in Sector 56 Gurgaon,nan,4 Crore,"₹ 26,613/sq.ft.",(140 sq.m.) Plot Area,Plot area 167(139.63 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 56 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...","Two storey property adjacent to park , close p...","['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '2 Ge...","['Private Garden / Terrace', 'Water Storage', ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
415,4 Bedroom House for sale in DLF Phase 4,nan,4.5 Crore,"₹ 125,000/sq.ft.",(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),4 Bedrooms,4 Bathrooms,No Balcony,NaN,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4 Floors,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [298]:
data['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
8 Crore             13
5 Crore             13
4.5 Crore           13
50 Lac              13
70 Lac              13
75 Lac              13
85 Lac              12
2.5 Crore           12
8.5 Crore           12
7 Crore             12
4 Crore             11
1.5 Crore           11
60 Lac              10
45 Lac              10
Price on Request    10
90 Lac              10
10 Crore            10
9 Crore             10
2.25 Crore          10
80 Lac               9
1.7 Crore            9
9.5 Crore            9
1.1 Crore            9
12 Crore             9
2 Crore              9
1.6 Crore            8
4.6 Crore            8
1 Crore              8
6.75 Crore           8
11 Crore             8
3.75 Crore           8
1.2 Crore            7
2.1 Crore            7
1.3 Crore            7
65 Lac               7
95 Lac               7
55 Lac               7
40 Lac               7
1.35 Crore           7
12.5 Crore           7
1.45 Crore           6
2.95 Crore           6
7.5 Crore            6
5.7 Crore            6
4.25 Crore           6
3.25 Crore           6
13.5 Crore           6
5.6 Crore            6
2.75 Crore           6
6.25 Crore           6
1.15 Crore           6
7.25 Crore           6
10.5 Crore           6
16 Crore             6
3.6 Crore            6
35 Lac               5
5.75 Crore           5
4.75 Crore           5
15 Crore             5
2.8 Crore            5
3 Crore              5
17 Crore             5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
8.25 Crore           5
9.25 Crore           4
18 Crore             4
4.35 Crore           4
2.4 Crore            4
42 Lac               4
1.65 Crore           4
4.7 Crore            4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
13 Crore             4
8.4 Crore            4
6.8 Crore            4
11.5 Crore           4
3.2 Crore            4
5.8 Crore            4
3.3 Crore            4
62 Lac               3
7.2 Crore            3
49 Lac               3
3.85 Crore           3
4.45 Crore           3
82 Lac               3
3.55 Crore           3
1.16 Crore           3
2.3 Crore            3
1.9 Crore            3
34 Lac               3
1.55 Crore           3
20 Crore             3
2.2 Crore            3
3.1 Crore            3
5.65 Crore           3
2.9 Crore            3
1.95 Crore           3
5.15 Crore           3
92 Lac               3
6.4 Crore            3
1.85 Crore           3
2.55 Crore           3
4.3 Crore            3
7.35 Crore           3
19 Crore             3
6.95 Crore           3
3.4 Crore            3
32 Lac               3
4.95 Crore           2
58 Lac               2
58.25 Lac            2
14 Crore             2
2.15 Crore           2
9.9 Crore            2
89 Lac               2
1.05 Crore           2
3.51 Crore           2
3.15 Crore           2
3.35 Crore           2
8.49 Crore           2
10.85 Crore          2
5.4 Crore            2
11.95 Crore          2
36 Lac               2
3.65 Crore           2
26 Crore             2
10.55 Crore          2
3.05 Crore           2
7.1 Crore            2
6.3 Crore            2
11.25 Crore          2
15.5 Crore           2
48 Lac               2
11.75 Crore          2
67 Lac               2
19.5 Crore           2
10.45 Crore          2
1.75 Crore           2
7.99 Crore           2
30 Lac               2
66 Lac               2
10.3 Crore           1
2.47 Crore           1
3.7 Crore            1
7.3 Crore            1
4.15 Crore           1
18.4 Crore           1
22 Crore             1
6.15 Crore           1
4.4 Crore            1
8.45 Crore           1
46.75 Lac            1
9.4 Crore            1
18.5 Crore           1
12.25 Crore          1
27.5 Crore           1
52.75 Lac            1
5.88 Crore           1
8.31 Crore           1
6.21 Crore           1
2.01 Crore           1
3.9 Crore            1
5.1 Crore            1
1.83 Crore           1
99 Lac               1
2.45 Crore           1
2.65 Crore           1
1.18 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
15.1 Crore           1
9.85 Crore           1
1.27 Crore           1
1.04 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
8.9 Crore            1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
4.49 Crore           1
65.8 Lac             1
8.81 Crore           1
55.11 Lac            1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
5.46 Crore           1
52 Lac               1
10.56 Crore          1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
3.12 Crore           1
7.49 Crore           1
6.81 Crore           1
22 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
6.6 Crore            1
5.35 Crore           1
5.85 Crore           1
5.9 Crore            1
6.2 Crore            1
3.93 Crore           1
8.7 Crore            1
7.69 Crore           1
15.5 Lac             1
8.8 Crore            1
4.12 Crore           1
1.87 Crore           1
12.39 Crore          1
7.6 Crore            1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
61 Lac               1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
18.02 Crore          1
10.75 Crore          1
96 Lac               1
24 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
44 Lac               1
13 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [299]:
def clean_price_col(row):
    if 'lac' in row:
        return round(float(row.split(' ')[0])/100, 2)
    elif 'crore' in row:
        return round(float(row.split(' ')[0]), 2)
    else:
        return row

data['price'] = data['price'].str.strip().str.lower().astype(str).apply(clean_price_col)

In [300]:
data['price'].value_counts(dropna=False)

price
nan                 127
3.5                  19
5.5                  17
6.5                  16
6.0                  14
8.0                  13
5.0                  13
4.5                  13
0.75                 13
0.5                  13
0.7                  13
7.0                  12
2.5                  12
0.85                 12
8.5                  12
1.5                  11
0.6                  11
4.0                  11
9.0                  10
0.9                  10
price on request     10
2.25                 10
10.0                 10
0.45                 10
9.5                   9
0.8                   9
1.1                   9
1.7                   9
12.0                  9
2.0                   9
0.55                  8
1.0                   8
11.0                  8
6.75                  8
3.75                  8
1.6                   8
4.6                   8
2.1                   7
12.5                  7
1.35                  7
1.3                   7
1.2                   7
0.4                   7
0.65                  7
0.95                  7
16.0                  6
1.15                  6
7.5                   6
3.6                   6
5.7                   6
3.25                  6
2.95                  6
7.25                  6
13.5                  6
5.6                   6
2.75                  6
10.5                  6
1.45                  6
6.25                  6
4.25                  6
17.0                  5
3.0                   5
5.75                  5
1.25                  5
15.0                  5
0.38                  5
1.8                   5
8.25                  5
4.75                  5
0.35                  5
2.8                   5
0.37                  4
0.42                  4
2.4                   4
0.58                  4
5.25                  4
18.0                  4
4.35                  4
13.0                  4
5.8                   4
8.4                   4
4.7                   4
1.4                   4
3.3                   4
3.2                   4
11.5                  4
9.25                  4
6.8                   4
1.65                  4
0.82                  3
1.9                   3
19.0                  3
2.9                   3
6.4                   3
0.62                  3
4.3                   3
0.47                  3
1.85                  3
0.92                  3
1.16                  3
0.34                  3
0.53                  3
0.49                  3
2.3                   3
5.15                  3
0.32                  3
2.2                   3
3.1                   3
20.0                  3
1.95                  3
4.45                  3
3.4                   3
7.2                   3
2.55                  3
3.55                  3
5.65                  3
1.55                  3
3.85                  3
7.35                  3
6.95                  3
0.66                  3
10.45                 2
7.99                  2
0.67                  2
0.48                  2
4.95                  2
19.5                  2
1.05                  2
3.51                  2
11.25                 2
1.75                  2
10.85                 2
2.15                  2
9.9                   2
5.4                   2
0.89                  2
11.95                 2
3.15                  2
3.35                  2
7.1                   2
8.49                  2
14.0                  2
0.36                  2
15.5                  2
11.75                 2
26.0                  2
10.55                 2
0.3                   2
6.3                   2
3.65                  2
3.05                  2
27.5                  1
2.47                  1
3.7                   1
18.4                  1
0.99                  1
4.4                   1
2.65                  1
1.27                  1
11.29                 1
18.5                  1
6.15                  1
1.83                  1
8.31                  1
8.45                  1
6.21                  1
2.01                  1
10.3                  1
9.4                   1
3.93                  1
12.25                 1
5.88                  1
4.31                  1
5.1                   1
3.9                   1
0.61                  1
9.35                  1
11.58                 1
9.01                  1
4.99                  1
8.6                   1
9.55                  1
2.35                  1
18.25                 1
5.3                   1
10.8                  1
31.5                  1
4.1                   1
7.65                  1
6.46                  1
6.44                  1
7.8                   1
3.8                   1
7.45                  1
7.42                  1
6.09                  1
9.8                   1
15.1                  1
8.48                  1
1.18                  1
8.2                   1
5.51                  1
3.49                  1
2.99                  1
9.19                  1
1.64                  1
10.75                 1
4.05                  1
8.75                  1
23.0                  1
2.45                  1
7.85                  1
25.0                  1
2.68                  1
2.7                   1
1.04                  1
9.85                  1
7.3                   1
17.3                  1
4.15                  1
6.1                   1
1.72                  1
0.78                  1
1.52                  1
8.8                   1
11.3                  1
0.52                  1
4.65                  1
0.68                  1
22.0                  1
1.07                  1
5.2                   1
12.39                 1
0.43                  1
7.49                  1
0.71                  1
4.02                  1
0.63                  1
0.51                  1
13.2                  1
8.95                  1
6.6                   1
4.12                  1
1.87                  1
5.35                  1
5.85                  1
5.9                   1
0.22                  1
6.2                   1
8.7                   1
7.05                  1
3.69                  1
3.12                  1
0.07                  1
2.58                  1
7.69                  1
1.44                  1
3.71                  1
0.18                  1
2.6                   1
1.39                  1
0.59                  1
0.15                  1
0.27                  1
8.1                   1
14.75                 1
9.54                  1
18.9                  1
24.0                  1
7.46                  1
3.99                  1
6.81                  1
8.81                  1
8.9                   1
4.49                  1
3.87                  1
0.46                  1
3.08                  1
1.34                  1
5.46                  1
0.29                  1
0.24                  1
0.44                  1
0.83                  1
0.98                  1
3.09                  1
0.74                  1
0.69                  1
2.43                  1
0.13                  1
0.96                  1
10.56                 1
18.02                 1
7.6                   1
2.98                  1
Name: count, dtype: int64

In [301]:
data['price'].value_counts()

price
nan                 127
3.5                  19
5.5                  17
6.5                  16
6.0                  14
8.0                  13
5.0                  13
4.5                  13
0.75                 13
0.5                  13
0.7                  13
7.0                  12
2.5                  12
0.85                 12
8.5                  12
1.5                  11
0.6                  11
4.0                  11
9.0                  10
0.9                  10
price on request     10
2.25                 10
10.0                 10
0.45                 10
9.5                   9
0.8                   9
1.1                   9
1.7                   9
12.0                  9
2.0                   9
0.55                  8
1.0                   8
11.0                  8
6.75                  8
3.75                  8
1.6                   8
4.6                   8
2.1                   7
12.5                  7
1.35                  7
1.3                   7
1.2                   7
0.4                   7
0.65                  7
0.95                  7
16.0                  6
1.15                  6
7.5                   6
3.6                   6
5.7                   6
3.25                  6
2.95                  6
7.25                  6
13.5                  6
5.6                   6
2.75                  6
10.5                  6
1.45                  6
6.25                  6
4.25                  6
17.0                  5
3.0                   5
5.75                  5
1.25                  5
15.0                  5
0.38                  5
1.8                   5
8.25                  5
4.75                  5
0.35                  5
2.8                   5
0.37                  4
0.42                  4
2.4                   4
0.58                  4
5.25                  4
18.0                  4
4.35                  4
13.0                  4
5.8                   4
8.4                   4
4.7                   4
1.4                   4
3.3                   4
3.2                   4
11.5                  4
9.25                  4
6.8                   4
1.65                  4
0.82                  3
1.9                   3
19.0                  3
2.9                   3
6.4                   3
0.62                  3
4.3                   3
0.47                  3
1.85                  3
0.92                  3
1.16                  3
0.34                  3
0.53                  3
0.49                  3
2.3                   3
5.15                  3
0.32                  3
2.2                   3
3.1                   3
20.0                  3
1.95                  3
4.45                  3
3.4                   3
7.2                   3
2.55                  3
3.55                  3
5.65                  3
1.55                  3
3.85                  3
7.35                  3
6.95                  3
0.66                  3
10.45                 2
7.99                  2
0.67                  2
0.48                  2
4.95                  2
19.5                  2
1.05                  2
3.51                  2
11.25                 2
1.75                  2
10.85                 2
2.15                  2
9.9                   2
5.4                   2
0.89                  2
11.95                 2
3.15                  2
3.35                  2
7.1                   2
8.49                  2
14.0                  2
0.36                  2
15.5                  2
11.75                 2
26.0                  2
10.55                 2
0.3                   2
6.3                   2
3.65                  2
3.05                  2
27.5                  1
2.47                  1
3.7                   1
18.4                  1
0.99                  1
4.4                   1
2.65                  1
1.27                  1
11.29                 1
18.5                  1
6.15                  1
1.83                  1
8.31                  1
8.45                  1
6.21                  1
2.01                  1
10.3                  1
9.4                   1
3.93                  1
12.25                 1
5.88                  1
4.31                  1
5.1                   1
3.9                   1
0.61                  1
9.35                  1
11.58                 1
9.01                  1
4.99                  1
8.6                   1
9.55                  1
2.35                  1
18.25                 1
5.3                   1
10.8                  1
31.5                  1
4.1                   1
7.65                  1
6.46                  1
6.44                  1
7.8                   1
3.8                   1
7.45                  1
7.42                  1
6.09                  1
9.8                   1
15.1                  1
8.48                  1
1.18                  1
8.2                   1
5.51                  1
3.49                  1
2.99                  1
9.19                  1
1.64                  1
10.75                 1
4.05                  1
8.75                  1
23.0                  1
2.45                  1
7.85                  1
25.0                  1
2.68                  1
2.7                   1
1.04                  1
9.85                  1
7.3                   1
17.3                  1
4.15                  1
6.1                   1
1.72                  1
0.78                  1
1.52                  1
8.8                   1
11.3                  1
0.52                  1
4.65                  1
0.68                  1
22.0                  1
1.07                  1
5.2                   1
12.39                 1
0.43                  1
7.49                  1
0.71                  1
4.02                  1
0.63                  1
0.51                  1
13.2                  1
8.95                  1
6.6                   1
4.12                  1
1.87                  1
5.35                  1
5.85                  1
5.9                   1
0.22                  1
6.2                   1
8.7                   1
7.05                  1
3.69                  1
3.12                  1
0.07                  1
2.58                  1
7.69                  1
1.44                  1
3.71                  1
0.18                  1
2.6                   1
1.39                  1
0.59                  1
0.15                  1
0.27                  1
8.1                   1
14.75                 1
9.54                  1
18.9                  1
24.0                  1
7.46                  1
3.99                  1
6.81                  1
8.81                  1
8.9                   1
4.49                  1
3.87                  1
0.46                  1
3.08                  1
1.34                  1
5.46                  1
0.29                  1
0.24                  1
0.44                  1
0.83                  1
0.98                  1
3.09                  1
0.74                  1
0.69                  1
2.43                  1
0.13                  1
0.96                  1
10.56                 1
18.02                 1
7.6                   1
2.98                  1
Name: count, dtype: int64

In [302]:
data = data[data['price']!='price on request']

In [303]:
data.rename(columns={'price':'price_in_crores'}, inplace=True)

In [304]:
data.sample(3)

,property_name,society,price_in_crores,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
368,12 Bedroom House for sale in Heera Nagar,nan,nan,"₹ 13,333/sq.ft.",(84 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1053,8 Bedroom House for sale in Sector 38 Gurgaon,sector 38 rwa,1.4,"₹ 23,932/sq.ft.",(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.)Built Up area: 62 sq....,8 Bedrooms,8 Bathrooms,3 Balconies,Others,"65 Sq Yd, 8 Rooms, 75k Rent Demand 1.40 Cr, Se...",4 Floors,East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stat...","This is a good investment for investors, total...","['11 Wardrobe', '7 Fan', '1 Exhaust Fan', '11 ...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Safety4 out of 5', ..."
312,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,nan,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN

# rate

In [305]:
data['rate'].str.split('/').str[0].str.split(' ').str[1].str.replace(',', '').value_counts(dropna=False)

rate
NaN       31
22222     14
11111     12
33333     11
10000     10
13333      7
37037      7
8000       6
26235      6
26667      6
30556      6
31481      6
23333      5
5000       5
11100      5
23148      5
9444       5
32407      5
8889       5
9722       4
24691      4
35000      4
21605      4
6944       4
15625      4
18889      4
7058       4
34722      4
25000      4
27778      4
25926      3
24500      3
17284      3
36111      3
29880      3
25562      3
12000      3
100000     3
6666       3
11250      3
9259       3
8235       3
17037      3
15555      3
44444      3
14815      3
13889      3
5555       3
20000      3
8444       3
7500       3
50000      3
10556      3
16058      3
32222      3
8333       3
60000      3
33951      3
45833      3
23457      3
12222      3
39841      2
37627      2
26389      2
11574      2
3857       2
21759      2
24845      2
75000      2
12963      2
9634       2
32328      2
10518      2
24306      2
9000       2
12342      2
29630      2
12500      2
10753      2
7407       2
32963      2
42222      2
38194      2
8888       2
12444      2
26852      2
3500       2
20635      2
20833      2
21242      2
7777       2
14444      2
11852      2
15257      2
24155      2
10101      2
59259      2
4444       2
27971      2
15700      2
13910      2
7619       2
35185      2
35556      2
13622      2
18928      2
37777      2
12519      2
17187      2
16039      2
21000      2
38760      2
201388     2
7718       2
25535      2
15278      2
42194      2
10579      2
1859       2
19708      2
12027      2
19000      2
20690      2
55000      2
21124      2
38095      2
13000      2
48148      2
38580      2
10783      2
27461      2
29716      2
16378      2
16975      2
17778      2
5333       2
23437      1
6000       1
18888      1
13492      1
7727       1
82540      1
26428      1
21495      1
19360      1
13178      1
11157      1
20741      1
19268      1
1560       1
15989      1
42054      1
13750      1
13501      1
24171      1
26973      1
11600      1
32253      1
20940      1
5950       1
20068      1
8702       1
10601      1
45710      1
20988      1
63554      1
27222      1
57206      1
32562      1
22429      1
39530      1
23704      1
23693      1
17662      1
23061      1
31686      1
178571     1
261194     1
22812      1
6778       1
29697      1
23000      1
38889      1
26298      1
24366      1
18626      1
21296      1
400000     1
16569      1
6938       1
18444      1
10591      1
7555       1
49500      1
13030      1
308333     1
8101       1
10610      1
7302       1
8155       1
24074      1
194444     1
5160       1
144444     1
7333       1
9615       1
6813       1
15046      1
11583      1
6034       1
14184      1
8127       1
160000     1
10484      1
7539       1
10067      1
1649       1
84000      1
28898      1
28200      1
7168       1
9390       1
10582      1
20444      1
6289       1
17857      1
7000       1
14166      1
30968      1
4260       1
18658      1
10085      1
40611      1
29629      1
39074      1
23442      1
41833      1
600000     1
23889      1
10260      1
31915      1
11102      1
8866       1
36911      1
15444      1
11240      1
15437      1
14351      1
27191      1
241666     1
33592      1
24455      1
38734      1
14890      1
10740      1
29444      1
17980      1
6800       1
19737      1
5093       1
2716       1
25463      1
7007       1
8920       1
35294      1
8254       1
5128       1
5777       1
9210       1
15926      1
14285      1
34307      1
51864      1
44265      1
20115      1
40850      1
27160      1
41315      1
3786       1
9349       1
23504      1
234375     1
21786      1
15432      1
21251      1
35530      1
18088      1
22046      1
27132      1
22855      1
40741      1
29333      1
290948     1
12393      1
22331      1
30728      1
27390      1
18250      1
16319      1
22184      1
30247      1
20370      1
31666      1
283333     1
18008      1
12285      1
19293      1
20599      1
173992     1
21367      1
20299      1
41818      1
19231      1
6875       1
14667      1
14787      1
20317      1
16600      1
24510      1
20566      1
16071      1
51440      1
28782      1
34491      1
34351      1
47803      1
6230       1
33665      1
20349      1
21219      1
24202      1
23870      1
20026      1
28787      1
12551      1
33129      1
13992      1
31008      1
23240      1
33404      1
32870      1
24005      1
19125      1
18885      1
15000      1
18814      1
14000      1
266666     1
26502      1
18808      1
10838      1
19847      1
12037      1
17820      1
24390      1
26063      1
79365      1
23932      1
24573      1
11428      1
38986      1
26111      1
23556      1
38611      1
27911      1
29022      1
12837      1
12198      1
35741      1
16666      1
7827       1
10035      1
1087       1
28841      1
26615      1
62222      1
16003      1
6597       1
7870       1
28233      1
15111      1
31926      1
43210      1
27083      1
31444      1
31790      1
235376     1
29293      1
16004      1
27333      1
17624      1
30864      1
161849     1
16056      1
17707      1
10926      1
19608      1
8089       1
6849       1
19607      1
40000      1
34846      1
19820      1
19645      1
55556      1
17213      1
25556      1
7756       1
21825      1
16577      1
17706      1
29074      1
37778      1
31111      1
18620      1
36883      1
17014      1
7750       1
7172       1
29638      1
8137       1
7582       1
18605      1
16066      1
21097      1
34568      1
20769      1
13513      1
27871      1
35109      1
17692      1
38022      1
25309      1
16990      1
14222      1
16388      1
22075      1
11666      1
47167      1
7937       1
20197      1
34037      1
10123      1
28858      1
28549      1
9103       1
8730       1
7400       1
4666       1
40775      1
99173      1
6172       1
9111       1
80357      1
4117       1
7308       1
8701       1
2296       1
9793       1
6250       1
8486       1
11717      1
7589       1
12592      1
15384      1
7843       1
7778       1
7666       1
102941     1
138888     1
24912      1
255555     1
4333       1
11784      1
13359      1
197080     1
13131      1
74074      1
10233      1
8878       1
14286      1
8928       1
8007       1
5698       1
28283      1
24214      1
26613      1
29336      1
10288      1
11284      1
11029      1
57692      1
10482      1
25386      1
8735       1
18667      1
2525       1
17695      1
21519      1
17817      1
2          1
6173       1
13888      1
20323      1
20359      1
5833       1
11693      1
53125      1
5472       1
20425      1
21667      1
230547     1
10277      1
8518       1
10555      1
557        1
8947       1
39265      1
6083       1
8411       1
9333       1
32291      1
41666      1
7280       1
90000      1
10089      1
8697       1
8500       1
29321      1
13071      1
7479       1
122222     1
19097      1
7290       1
27741      1
43534      1
45889      1
13909      1
35400      1
13623      1
13331      1
40135      1
16244      1
16999      1
10714      1
10463      1
18750      1
27793      1
22006      1
13542      1
28490      1
24444      1
24170      1
38251      1
43066      1
53763      1
39062      1
48889      1
38150      1
10077      1
34083      1
33200      1
14914      1
29861      1
41762      1
15451      1
12938      1
9374       1
13410      1
32593      1
28760      1
41615      1
38703      1
12828      1
86567      1
92857      1
88157      1
29974      1
2778       1
46906      1
23699      1
25960      1
28424      1
4490       1
14729      1
25111      1
7309       1
8181       1
43333      1
481        1
3452       1
630        1
4074       1
9028       1
13778      1
12842      1
8557       1
16428      1
13519      1
42032      1
24069      1
14650      1
21250      1
36667      1
38667      1
12593      1
25514      1
17650      1
24280      1
26423      1
8916       1
17900      1
39886      1
126865     1
7111       1
183333     1
10142      1
8125       1
14583      1
11538      1
105751     1
8230       1
13095      1
29311      1
30384      1
19818      1
1992       1
98214      1
13499      1
7820       1
4000       1
14720      1
8012       1
9135       1
40909      1
11904      1
16389      1
31506      1
12820      1
229885     1
12400      1
232        1
218750     1
54794      1
14245      1
6367       1
37313      1
90909      1
10122      1
8642       1
6481       1
6707       1
245398     1
5664       1
19753      1
76000      1
63492      1
3254       1
4583       1
21875      1
16667      1
7075       1
8078       1
4251       1
17584      1
5397       1
9074       1
5583       1
3519       1
11194      1
6981       1
6702       1
18333      1
4877       1
17937      1
9500       1
26620      1
20062      1
2500       1
6667       1
3704       1
12777      1
6648       1
11407      1
20233      1
11494      1
181818     1
25543      1
12343      1
16892      1
17500      1
3904       1
14323      1
4222       1
32258      1
11888      1
10378      1
24305      1
10134      1
9375       1
4400       1
13636      1
28674      1
9725       1
21111      1
10784      1
12162      1
8910       1
19869      1
8796       1
7522       1
5658       1
24545      1
7701       1
14072      1
15097      1
12778      1
8386       1
7875       1
27155      1
14492      1
14045      1
10804      1
14167      1
13157      1
5888       1
9654       1
66666      1
4808       1
8222       1
11273      1
7627       1
5666       1
6567       1
22068      1
26000      1
19286      1
11556      1
22634      1
23662      1
17574      1
9091       1
23557      1
105263     1
21195      1
151        1
25103      1
14954      1
8784       1
6500       1
35494      1
11464      1
11718      1
11555      1
3874       1
7576       1
27139      1
74000      1
3285       1
7916       1
26570      1
6410       1
133079     1
5778       1
6111       1
78125      1
17955      1
211111     1
10224      1
80000      1
120000     1
22297      1
125000     1
73333      1
6790       1
315789     1
13034      1
Name: count, dtype: int64

In [306]:
data['rate'] = data['rate'].str.split('/').str[0].str.split(' ').str[1].str.replace(',', '')

In [307]:
data['rate'].value_counts(dropna=False)

rate
NaN       31
22222     14
11111     12
33333     11
10000     10
13333      7
37037      7
8000       6
26235      6
26667      6
30556      6
31481      6
23333      5
5000       5
11100      5
23148      5
9444       5
32407      5
8889       5
9722       4
24691      4
35000      4
21605      4
6944       4
15625      4
18889      4
7058       4
34722      4
25000      4
27778      4
25926      3
24500      3
17284      3
36111      3
29880      3
25562      3
12000      3
100000     3
6666       3
11250      3
9259       3
8235       3
17037      3
15555      3
44444      3
14815      3
13889      3
5555       3
20000      3
8444       3
7500       3
50000      3
10556      3
16058      3
32222      3
8333       3
60000      3
33951      3
45833      3
23457      3
12222      3
39841      2
37627      2
26389      2
11574      2
3857       2
21759      2
24845      2
75000      2
12963      2
9634       2
32328      2
10518      2
24306      2
9000       2
12342      2
29630      2
12500      2
10753      2
7407       2
32963      2
42222      2
38194      2
8888       2
12444      2
26852      2
3500       2
20635      2
20833      2
21242      2
7777       2
14444      2
11852      2
15257      2
24155      2
10101      2
59259      2
4444       2
27971      2
15700      2
13910      2
7619       2
35185      2
35556      2
13622      2
18928      2
37777      2
12519      2
17187      2
16039      2
21000      2
38760      2
201388     2
7718       2
25535      2
15278      2
42194      2
10579      2
1859       2
19708      2
12027      2
19000      2
20690      2
55000      2
21124      2
38095      2
13000      2
48148      2
38580      2
10783      2
27461      2
29716      2
16378      2
16975      2
17778      2
5333       2
23437      1
6000       1
18888      1
13492      1
7727       1
82540      1
26428      1
21495      1
19360      1
13178      1
11157      1
20741      1
19268      1
1560       1
15989      1
42054      1
13750      1
13501      1
24171      1
26973      1
11600      1
32253      1
20940      1
5950       1
20068      1
8702       1
10601      1
45710      1
20988      1
63554      1
27222      1
57206      1
32562      1
22429      1
39530      1
23704      1
23693      1
17662      1
23061      1
31686      1
178571     1
261194     1
22812      1
6778       1
29697      1
23000      1
38889      1
26298      1
24366      1
18626      1
21296      1
400000     1
16569      1
6938       1
18444      1
10591      1
7555       1
49500      1
13030      1
308333     1
8101       1
10610      1
7302       1
8155       1
24074      1
194444     1
5160       1
144444     1
7333       1
9615       1
6813       1
15046      1
11583      1
6034       1
14184      1
8127       1
160000     1
10484      1
7539       1
10067      1
1649       1
84000      1
28898      1
28200      1
7168       1
9390       1
10582      1
20444      1
6289       1
17857      1
7000       1
14166      1
30968      1
4260       1
18658      1
10085      1
40611      1
29629      1
39074      1
23442      1
41833      1
600000     1
23889      1
10260      1
31915      1
11102      1
8866       1
36911      1
15444      1
11240      1
15437      1
14351      1
27191      1
241666     1
33592      1
24455      1
38734      1
14890      1
10740      1
29444      1
17980      1
6800       1
19737      1
5093       1
2716       1
25463      1
7007       1
8920       1
35294      1
8254       1
5128       1
5777       1
9210       1
15926      1
14285      1
34307      1
51864      1
44265      1
20115      1
40850      1
27160      1
41315      1
3786       1
9349       1
23504      1
234375     1
21786      1
15432      1
21251      1
35530      1
18088      1
22046      1
27132      1
22855      1
40741      1
29333      1
290948     1
12393      1
22331      1
30728      1
27390      1
18250      1
16319      1
22184      1
30247      1
20370      1
31666      1
283333     1
18008      1
12285      1
19293      1
20599      1
173992     1
21367      1
20299      1
41818      1
19231      1
6875       1
14667      1
14787      1
20317      1
16600      1
24510      1
20566      1
16071      1
51440      1
28782      1
34491      1
34351      1
47803      1
6230       1
33665      1
20349      1
21219      1
24202      1
23870      1
20026      1
28787      1
12551      1
33129      1
13992      1
31008      1
23240      1
33404      1
32870      1
24005      1
19125      1
18885      1
15000      1
18814      1
14000      1
266666     1
26502      1
18808      1
10838      1
19847      1
12037      1
17820      1
24390      1
26063      1
79365      1
23932      1
24573      1
11428      1
38986      1
26111      1
23556      1
38611      1
27911      1
29022      1
12837      1
12198      1
35741      1
16666      1
7827       1
10035      1
1087       1
28841      1
26615      1
62222      1
16003      1
6597       1
7870       1
28233      1
15111      1
31926      1
43210      1
27083      1
31444      1
31790      1
235376     1
29293      1
16004      1
27333      1
17624      1
30864      1
161849     1
16056      1
17707      1
10926      1
19608      1
8089       1
6849       1
19607      1
40000      1
34846      1
19820      1
19645      1
55556      1
17213      1
25556      1
7756       1
21825      1
16577      1
17706      1
29074      1
37778      1
31111      1
18620      1
36883      1
17014      1
7750       1
7172       1
29638      1
8137       1
7582       1
18605      1
16066      1
21097      1
34568      1
20769      1
13513      1
27871      1
35109      1
17692      1
38022      1
25309      1
16990      1
14222      1
16388      1
22075      1
11666      1
47167      1
7937       1
20197      1
34037      1
10123      1
28858      1
28549      1
9103       1
8730       1
7400       1
4666       1
40775      1
99173      1
6172       1
9111       1
80357      1
4117       1
7308       1
8701       1
2296       1
9793       1
6250       1
8486       1
11717      1
7589       1
12592      1
15384      1
7843       1
7778       1
7666       1
102941     1
138888     1
24912      1
255555     1
4333       1
11784      1
13359      1
197080     1
13131      1
74074      1
10233      1
8878       1
14286      1
8928       1
8007       1
5698       1
28283      1
24214      1
26613      1
29336      1
10288      1
11284      1
11029      1
57692      1
10482      1
25386      1
8735       1
18667      1
2525       1
17695      1
21519      1
17817      1
2          1
6173       1
13888      1
20323      1
20359      1
5833       1
11693      1
53125      1
5472       1
20425      1
21667      1
230547     1
10277      1
8518       1
10555      1
557        1
8947       1
39265      1
6083       1
8411       1
9333       1
32291      1
41666      1
7280       1
90000      1
10089      1
8697       1
8500       1
29321      1
13071      1
7479       1
122222     1
19097      1
7290       1
27741      1
43534      1
45889      1
13909      1
35400      1
13623      1
13331      1
40135      1
16244      1
16999      1
10714      1
10463      1
18750      1
27793      1
22006      1
13542      1
28490      1
24444      1
24170      1
38251      1
43066      1
53763      1
39062      1
48889      1
38150      1
10077      1
34083      1
33200      1
14914      1
29861      1
41762      1
15451      1
12938      1
9374       1
13410      1
32593      1
28760      1
41615      1
38703      1
12828      1
86567      1
92857      1
88157      1
29974      1
2778       1
46906      1
23699      1
25960      1
28424      1
4490       1
14729      1
25111      1
7309       1
8181       1
43333      1
481        1
3452       1
630        1
4074       1
9028       1
13778      1
12842      1
8557       1
16428      1
13519      1
42032      1
24069      1
14650      1
21250      1
36667      1
38667      1
12593      1
25514      1
17650      1
24280      1
26423      1
8916       1
17900      1
39886      1
126865     1
7111       1
183333     1
10142      1
8125       1
14583      1
11538      1
105751     1
8230       1
13095      1
29311      1
30384      1
19818      1
1992       1
98214      1
13499      1
7820       1
4000       1
14720      1
8012       1
9135       1
40909      1
11904      1
16389      1
31506      1
12820      1
229885     1
12400      1
232        1
218750     1
54794      1
14245      1
6367       1
37313      1
90909      1
10122      1
8642       1
6481       1
6707       1
245398     1
5664       1
19753      1
76000      1
63492      1
3254       1
4583       1
21875      1
16667      1
7075       1
8078       1
4251       1
17584      1
5397       1
9074       1
5583       1
3519       1
11194      1
6981       1
6702       1
18333      1
4877       1
17937      1
9500       1
26620      1
20062      1
2500       1
6667       1
3704       1
12777      1
6648       1
11407      1
20233      1
11494      1
181818     1
25543      1
12343      1
16892      1
17500      1
3904       1
14323      1
4222       1
32258      1
11888      1
10378      1
24305      1
10134      1
9375       1
4400       1
13636      1
28674      1
9725       1
21111      1
10784      1
12162      1
8910       1
19869      1
8796       1
7522       1
5658       1
24545      1
7701       1
14072      1
15097      1
12778      1
8386       1
7875       1
27155      1
14492      1
14045      1
10804      1
14167      1
13157      1
5888       1
9654       1
66666      1
4808       1
8222       1
11273      1
7627       1
5666       1
6567       1
22068      1
26000      1
19286      1
11556      1
22634      1
23662      1
17574      1
9091       1
23557      1
105263     1
21195      1
151        1
25103      1
14954      1
8784       1
6500       1
35494      1
11464      1
11718      1
11555      1
3874       1
7576       1
27139      1
74000      1
3285       1
7916       1
26570      1
6410       1
133079     1
5778       1
6111       1
78125      1
17955      1
211111     1
10224      1
80000      1
120000     1
22297      1
125000     1
73333      1
6790       1
315789     1
13034      1
Name: count, dtype: int64

In [308]:
data.rename(columns={'rate':'price_per_sqft'}, inplace=True)

In [309]:
data.sample(3)

,property_name,society,price_in_crores,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
739,4 Bedroom House for sale in Sector 49 Gurgaon,eros rosewood city,1.6,31481,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,NaN,"E-103, Sector 49 Gurgaon, Gurgaon, Haryana",4 Floors,East,0 to 1 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",For those seeking good investment in rental in...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Water Storag...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
345,3 Bedroom House for sale in Arjun Nagar,nan,0.62,11273,(51 sq.m.) Built-up Area,Built Up area: 550 (51.1 sq.m.),3 Bedrooms,1 Bathroom,No Balcony,NaN,"Arjun Nagar, Sector 8, Arjun Nagar, Gurgaon, H...",2 Floors,NaN,undefined,NaN,Best in class property available at arjun naga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
328,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,nan,14045,(363 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

# area

In [310]:
data['area'].str.split(')')

0               [(242 sq.m.,  Plot Area]
1                [(50 sq.m.,  Plot Area]
2                [(51 sq.m.,  Plot Area]
3               [(108 sq.m.,  Plot Area]
4                [(52 sq.m.,  Plot Area]
5               [(107 sq.m.,  Plot Area]
6               [(301 sq.m.,  Plot Area]
7               [(418 sq.m.,  Plot Area]
8               [(264 sq.m.,  Plot Area]
9               [(180 sq.m.,  Plot Area]
10              [(125 sq.m.,  Plot Area]
11              [(301 sq.m.,  Plot Area]
12              [(136 sq.m.,  Plot Area]
13              [(420 sq.m.,  Plot Area]
14              [(251 sq.m.,  Plot Area]
15              [(125 sq.m.,  Plot Area]
16              [(334 sq.m.,  Plot Area]
17               [(84 sq.m.,  Plot Area]
18              [(201 sq.m.,  Plot Area]
19              [(268 sq.m.,  Plot Area]
20              [(244 sq.m.,  Plot Area]
21              [(293 sq.m.,  Plot Area]
22              [(301 sq.m.,  Plot Area]
23              [(301 sq.m.,  Plot Area]
24              [(180 sq.m.,  Plot Area]
25              [(251 sq.m.,  Plot Area]
26              [(471 sq.m.,  Plot Area]
27              [(242 sq.m.,  Plot Area]
28              [(220 sq.m.,  Plot Area]
29              [(301 sq.m.,  Plot Area]
30              [(210 sq.m.,  Plot Area]
31              [(251 sq.m.,  Plot Area]
32              [(293 sq.m.,  Plot Area]
33               [(84 sq.m.,  Plot Area]
34              [(134 sq.m.,  Plot Area]
35              [(161 sq.m.,  Plot Area]
36              [(251 sq.m.,  Plot Area]
37              [(300 sq.m.,  Plot Area]
38              [(251 sq.m.,  Plot Area]
39              [(251 sq.m.,  Plot Area]
40              [(167 sq.m.,  Plot Area]
41               [(70 sq.m.,  Plot Area]
42              [(251 sq.m.,  Plot Area]
43              [(251 sq.m.,  Plot Area]
44              [(255 sq.m.,  Plot Area]
45              [(251 sq.m.,  Plot Area]
46              [(167 sq.m.,  Plot Area]
47              [(293 sq.m.,  Plot Area]
48              [(242 sq.m.,  Plot Area]
49              [(180 sq.m.,  Plot Area]
50              [(145 sq.m.,  Plot Area]
51              [(301 sq.m.,  Plot Area]
52              [(418 sq.m.,  Plot Area]
53          [(593 sq.m.,  Built-up Area]
54              [(136 sq.m.,  Plot Area]
55              [(241 sq.m.,  Plot Area]
56              [(372 sq.m.,  Plot Area]
57              [(135 sq.m.,  Plot Area]
58              [(316 sq.m.,  Plot Area]
59              [(316 sq.m.,  Plot Area]
60              [(297 sq.m.,  Plot Area]
61              [(135 sq.m.,  Plot Area]
62              [(420 sq.m.,  Plot Area]
63              [(251 sq.m.,  Plot Area]
64              [(321 sq.m.,  Plot Area]
65              [(264 sq.m.,  Plot Area]
66              [(268 sq.m.,  Plot Area]
67              [(268 sq.m.,  Plot Area]
68               [(33 sq.m.,  Plot Area]
69               [(54 sq.m.,  Plot Area]
70              [(420 sq.m.,  Plot Area]
71              [(418 sq.m.,  Plot Area]
72              [(201 sq.m.,  Plot Area]
73          [(743 sq.m.,  Built-up Area]
74               [(84 sq.m.,  Plot Area]
75      [(467-681 sq.m.,  Built-up Area]
76      [(384-392 sq.m.,  Built-up Area]
77            [(232 sq.m.,  Carpet Area]
78              [(180 sq.m.,  Plot Area]
79      [(606-754 sq.m.,  Built-up Area]
80          [(521 sq.m.,  Built-up Area]
81      [(467-681 sq.m.,  Built-up Area]
82      [(294-418 sq.m.,  Built-up Area]
83          [(293 sq.m.,  Built-up Area]
84      [(590-687 sq.m.,  Built-up Area]
85          [(521 sq.m.,  Built-up Area]
86          [(606 sq.m.,  Built-up Area]
87          [(521 sq.m.,  Built-up Area]
88          [(543 sq.m.,  Built-up Area]
89      [(468-681 sq.m.,  Built-up Area]
90      [(292-358 sq.m.,  Built-up Area]
91          [(293 sq.m.,  Built-up Area]
92              [(220 sq.m.,  Plot Area]
93              [(286 sq.m.,  Plot Area]
94          [(606 sq.m.,  Built-up Area]
95          [(521 sq.m.,  Built-up Area]
96          [(325 sq.m.,  Built-up Area]
97          [(293 sq.m.,  Built-up Area]
98      [(139-279 sq.m.,  Built-up Area]
99      [(650-790 sq.m.,  Built-up Area]
100     [(590-687 sq.m.,  Built-up Area]
101     [(251-704 sq.m.,  Built-up Area]
102         [(211 sq.m.,  Built-up Area]
103             [(226 sq.m.,  Plot Area]
104             [(502 sq.m.,  Plot Area]
105     [(372-441 sq.m.,  Built-up Area]
106         [(279 sq.m.,  Built-up Area]
107     [(571-711 sq.m.,  Built-up Area]
108     [(372-441 sq.m.,  Built-up Area]
109         [(279 sq.m.,  Built-up Area]
110         [(543 sq.m.,  Built-up Area]
111     [(293-381 sq.m.,  Built-up Area]
112         [(207 sq.m.,  Built-up Area]
113         [(301 sq.m.,  Built-up Area]
114         [(223 sq.m.,  Built-up Area]
115     [(606-754 sq.m.,  Built-up Area]
116         [(521 sq.m.,  Built-up Area]
117         [(183 sq.m.,  Built-up Area]
118         [(344 sq.m.,  Built-up Area]
119             [(209 sq.m.,  Plot Area]
120             [(460 sq.m.,  Plot Area]
121             [(251 sq.m.,  Plot Area]
122             [(815 sq.m.,  Plot Area]
123         [(650 sq.m.,  Built-up Area]
124         [(650 sq.m.,  Built-up Area]
125             [(301 sq.m.,  Plot Area]
126              [(73 sq.m.,  Plot Area]
127              [(25 sq.m.,  Plot Area]
128         [(543 sq.m.,  Built-up Area]
129             [(502 sq.m.,  Plot Area]
130             [(220 sq.m.,  Plot Area]
131             [(254 sq.m.,  Plot Area]
132             [(297 sq.m.,  Plot Area]
133             [(301 sq.m.,  Plot Area]
134             [(100 sq.m.,  Plot Area]
135             [(244 sq.m.,  Plot Area]
136             [(134 sq.m.,  Plot Area]
137             [(209 sq.m.,  Plot Area]
138             [(134 sq.m.,  Plot Area]
139             [(223 sq.m.,  Plot Area]
140             [(372 sq.m.,  Plot Area]
141             [(209 sq.m.,  Plot Area]
142             [(418 sq.m.,  Plot Area]
143             [(502 sq.m.,  Plot Area]
144             [(334 sq.m.,  Plot Area]
145             [(502 sq.m.,  Plot Area]
146             [(226 sq.m.,  Plot Area]
147             [(135 sq.m.,  Plot Area]
148             [(161 sq.m.,  Plot Area]
149             [(226 sq.m.,  Plot Area]
150             [(206 sq.m.,  Plot Area]
151             [(557 sq.m.,  Plot Area]
152         [(557 sq.m.,  Built-up Area]
153             [(167 sq.m.,  Plot Area]
154         [(650 sq.m.,  Built-up Area]
155             [(743 sq.m.,  Plot Area]
156              [(67 sq.m.,  Plot Area]
157             [(125 sq.m.,  Plot Area]
158            [(1254 sq.m.,  Plot Area]
159               [(6 sq.m.,  Plot Area]
160               [(7 sq.m.,  Plot Area]
161               [(6 sq.m.,  Plot Area]
162               [(7 sq.m.,  Plot Area]
163             [(180 sq.m.,  Plot Area]
164             [(226 sq.m.,  Plot Area]
165            [(2592 sq.m.,  Plot Area]
166             [(140 sq.m.,  Plot Area]
167             [(167 sq.m.,  Plot Area]
168             [(145 sq.m.,  Plot Area]
169              [(89 sq.m.,  Plot Area]
170             [(180 sq.m.,  Plot Area]
171             [(418 sq.m.,  Plot Area]
172             [(201 sq.m.,  Plot Area]
173             [(360 sq.m.,  Plot Area]
174             [(418 sq.m.,  Plot Area]
175             [(418 sq.m.,  Plot Area]
176         [(511 sq.m.,  Built-up Area]
177             [(502 sq.m.,  Plot Area]
178             [(301 sq.m.,  Plot Area]
179             [(251 sq.m.,  Plot Area]
180             [(511 sq.m.,  Plot Area]
181             [(251 sq.m.,  Plot Area]
182              [(42 sq.m.,  Plot Area]
183             [(995 sq.m.,  Plot Area]
184         [(390 sq.m.,  Built-up Area]
185             [(209 sq.m.,  Plot Area]
186           [(6 sq.m.,  Built-up Area]
187             [(142 sq.m.,  Plot Area]
188             [(142 sq.m.,  Plot Area]
189              [(16 sq.m.,  Plot Area]
190             [(301 sq.m.,  Plot Area]
191             [(171 sq.m.,  Plot Area]
192         [(264 sq.m.,  Built-up Area]
193              [(33 sq.m.,  Plot Area]
194             [(151 sq.m.,  Plot Area]
195             [(139 sq.m.,  Plot Area]
196              [(84 sq.m.,  Plot Area]
197              [(70 sq.m.,  Plot Area]
198              [(13 sq.m.,  Plot Area]
199             [(184 sq.m.,  Plot Area]
200              [(13 sq.m.,  Plot Area]
201              [(51 sq.m.,  Plot Area]
202              [(64 sq.m.,  Plot Area]
203              [(50 sq.m.,  Plot Area]
204              [(99 sq.m.,  Plot Area]
205             [(293 sq.m.,  Plot Area]
206          [(94 sq.m.,  Built-up Area]
207              [(52 sq.m.,  Plot Area]
208              [(84 sq.m.,  Plot Area]
209              [(98 sq.m.,  Plot Area]
210             [(230 sq.m.,  Plot Area]
211             [(151 sq.m.,  Plot Area]
212             [(140 sq.m.,  Plot Area]
213               [(5 sq.m.,  Plot Area]
214              [(84 sq.m.,  Plot Area]
215         [(279 sq.m.,  Built-up Area]
216              [(63 sq.m.,  Plot Area]
217              [(56 sq.m.,  Plot Area]
218              [(84 sq.m.,  Plot Area]
219          [(42 sq.m.,  Built-up Area]
220               [(7 sq.m.,  Plot Area]
221              [(42 sq.m.,  Plot Area]
222            [(46 sq.m.,  Carpet Area]
223              [(91 sq.m.,  Plot Area]
224              [(22 sq.m.,  Plot Area]
225             [(167 sq.m.,  Plot Area]
226             [(166 sq.m.,  Plot Area]
227             [(334 sq.m.,  Plot Area]
228              [(84 sq.m.,  Plot Area]
229          [(10 sq.m.,  Built-up Area]
230             [(158 sq.m.,  Plot Area]
231         [(121 sq.m.,  Built-up Area]
232             [(139 sq.m.,  Plot Area]
233          [(42 sq.m.,  Built-up Area]
234             [(125 sq.m.,  Plot Area]
235             [(111 sq.m.,  Plot Area]
236              [(63 sq.m.,  Plot Area]
237              [(84 sq.m.,  Plot Area]
238             [(167 sq.m.,  Plot Area]
239             [(209 sq.m.,  Plot Area]
240             [(261 sq.m.,  Plot Area]
241           [(260 sq.m.,  Carpet Area]
242             [(339 sq.m.,  Plot Area]
243            [(92 sq.m.,  Carpet Area]
244         [(104 sq.m.,  Built-up Area]
245          [(63 sq.m.,  Built-up Area]
246              [(25 sq.m.,  Plot Area]
247           [(302 sq.m.,  Carpet Area]
248              [(43 sq.m.,  Plot Area]
249             [(209 sq.m.,  Plot Area]
250             [(418 sq.m.,  Plot Area]
251             [(253 sq.m.,  Plot Area]
252             [(135 sq.m.,  Plot Area]
253             [(107 sq.m.,  Plot Area]
254         [(316 sq.m.,  Built-up Area]
255              [(33 sq.m.,  Plot Area]
256           [(301 sq.m.,  Carpet Area]
257             [(125 sq.m.,  Plot Area]
258              [(84 sq.m.,  Plot Area]
259              [(33 sq.m.,  Plot Area]
260            [(2415 sq.m.,  Plot Area]
261              [(84 sq.m.,  Plot Area]
262             [(125 sq.m.,  Plot Area]
263              [(88 sq.m.,  Plot Area]
264             [(166 sq.m.,  Plot Area]
265          [(76 sq.m.,  Built-up Area]
266          [(32 sq.m.,  Built-up Area]
267            [(50 sq.m.,  Carpet Area]
268          [(18 sq.m.,  Built-up Area]
269          [(22 sq.m.,  Built-up Area]
270             [(431 sq.m.,  Plot Area]
271             [(121 sq.m.,  Plot Area]
272           [(5 sq.m.,  Built-up Area]
273              [(41 sq.m.,  Plot Area]
274         [(200 sq.m.,  Built-up Area]
275          [(93 sq.m.,  Built-up Area]
276          [(42 sq.m.,  Built-up Area]
277              [(52 sq.m.,  Plot Area]
278              [(84 sq.m.,  Plot Area]
279         [(279 sq.m.,  Built-up Area]
280             [(171 sq.m.,  Plot Area]
281             [(372 sq.m.,  Plot Area]
282             [(301 sq.m.,  Plot Area]
283          [(12 sq.m.,  Built-up Area]
284               [(5 sq.m.,  Plot Area]
285             [(251 sq.m.,  Plot Area]
286         [(325 sq.m.,  Built-up Area]
287             [(201 sq.m.,  Plot Area]
288              [(67 sq.m.,  Plot Area]
289            [(28 sq.m.,  Carpet Area]
290          [(20 sq.m.,  Built-up Area]
291          [(44 sq.m.,  Built-up Area]
292              [(84 sq.m.,  Plot Area]
293             [(133 sq.m.,  Plot Area]
294           [(167 sq.m.,  Carpet Area]
297         [(278 sq.m.,  Built-up Area]
298         [(139 sq.m.,  Built-up Area]
299             [(153 sq.m.,  Plot Area]
300              [(28 sq.m.,  Plot Area]
301           [(134 sq.m.,  Carpet Area]
302           [(121 sq.m.,  Carpet Area]
303         [(367 sq.m.,  Built-up Area]
304             [(209 sq.m.,  Plot Area]
305          [(809371 sq.m.,  Plot Area]
306              [(90 sq.m.,  Plot Area]
307              [(19 sq.m.,  Plot Area]
308     [(509-543 sq.m.,  Built-up Area]
309             [(167 sq.m.,  Plot Area]
310             [(160 sq.m.,  Plot Area]
311             [(135 sq.m.,  Plot Area]
312         [(344 sq.m.,  Built-up Area]
313         [(697 sq.m.,  Built-up Area]
314         [(111 sq.m.,  Built-up Area]
315              [(92 sq.m.,  Plot Area]
316         [(557 sq.m.,  Built-up Area]
317         [(149 sq.m.,  Built-up Area]
318             [(465 sq.m.,  Plot Area]
319         [(353 sq.m.,  Built-up Area]
320             [(326 sq.m.,  Plot Area]
321               [(6 sq.m.,  Plot Area]
322          [(31 sq.m.,  Built-up Area]
323         [(452 sq.m.,  Built-up Area]
324             [(385 sq.m.,  Plot Area]
327         [(540 sq.m.,  Built-up Area]
328         [(363 sq.m.,  Built-up Area]
329     [(468-681 sq.m.,  Built-up Area]
330     [(292-358 sq.m.,  Built-up Area]
331         [(293 sq.m.,  Built-up Area]
332              [(33 sq.m.,  Plot Area]
333          [(92 sq.m.,  Built-up Area]
334              [(93 sq.m.,  Plot Area]
335             [(177 sq.m.,  Plot Area]
336          [(84 sq.m.,  Built-up Area]
337             [(167 sq.m.,  Plot Area]
338          [(74 sq.m.,  Built-up Area]
339              [(34 sq.m.,  Plot Area]
340          [(87 sq.m.,  Built-up Area]
341              [(42 sq.m.,  Plot Area]
342         [(144 sq.m.,  Built-up Area]
343             [(325 sq.m.,  Plot Area]
344           [(9 sq.m.,  Built-up Area]
345          [(51 sq.m.,  Built-up Area]
346           [(929 sq.m.,  Carpet Area]
347         [(219 sq.m.,  Built-up Area]
348         [(279 sq.m.,  Built-up Area]
349         [(102 sq.m.,  Built-up Area]
350         [(279 sq.m.,  Built-up Area]
351         [(219 sq.m.,  Built-up Area]
352          [(13 sq.m.,  Built-up Area]
353              [(33 sq.m.,  Plot Area]
354            [(49 sq.m.,  Carpet Area]
355           [(7 sq.m.,  Built-up Area]
356         [(372 sq.m.,  Built-up Area]
357         [(233 sq.m.,  Built-up Area]
358          [(59 sq.m.,  Built-up Area]
359              [(84 sq.m.,  Plot Area]
360            [(84 sq.m.,  Carpet Area]
361         [(204 sq.m.,  Built-up Area]
362             [(209 sq.m.,  Plot Area]
363             [(308 sq.m.,  Plot Area]
364              [(83 sq.m.,  Plot Area]
365             [(220 sq.m.,  Plot Area]
366         [(112 sq.m.,  Built-up Area]
367             [(232 sq.m.,  Plot Area]
368              [(84 sq.m.,  Plot Area]
369              [(41 sq.m.,  Plot Area]
370             [(418 sq.m.,  Plot Area]
371          [(93 sq.m.,  Built-up Area]
372             [(167 sq.m.,  Plot Area]
373         [(201 sq.m.,  Built-up Area]
374              [(54 sq.m.,  Plot Area]
375              [(52 sq.m.,  Plot Area]
376            [(75 sq.m.,  Carpet Area]
377              [(42 sq.m.,  Plot Area]
378         [(478 sq.m.,  Built-up Area]
379              [(57 sq.m.,  Plot Area]
380              [(34 sq.m.,  Plot Area]
381              [(89 sq.m.,  Plot Area]
382             [(132 sq.m.,  Plot Area]
383              [(71 sq.m.,  Plot Area]
384             [(100 sq.m.,  Plot Area]
385         [(100 sq.m.,  Built-up Area]
386         [(105 sq.m.,  Built-up Area]
387              [(95 sq.m.,  Plot Area]
388            [(84 sq.m.,  Carpet Area]
389              [(51 sq.m.,  Plot Area]
390              [(84 sq.m.,  Plot Area]
391         [(158 sq.m.,  Built-up Area]
392         [(340 sq.m.,  Built-up Area]
393             [(232 sq.m.,  Plot Area]
394             [(134 sq.m.,  Plot Area]
395         [(650 sq.m.,  Built-up Area]
396             [(226 sq.m.,  Plot Area]
397             [(115 sq.m.,  Plot Area]
398             [(146 sq.m.,  Plot Area]
399             [(109 sq.m.,  Plot Area]
400              [(24 sq.m.,  Plot Area]
401          [(56 sq.m.,  Built-up Area]
403              [(84 sq.m.,  Plot Area]
404             [(167 sq.m.,  Plot Area]
405          [(45 sq.m.,  Built-up Area]
406          [(15 sq.m.,  Built-up Area]
407         [(220 sq.m.,  Built-up Area]
408          [(45 sq.m.,  Built-up Area]
409          [(25 sq.m.,  Built-up Area]
410               [(9 sq.m.,  Plot Area]
411            [(56 sq.m.,  Carpet Area]
412         [(102 sq.m.,  Built-up Area]
413               [(5 sq.m.,  Plot Area]
414              [(50 sq.m.,  Plot Area]
415          [(33 sq.m.,  Built-up Area]
416              [(84 sq.m.,  Plot Area]
417              [(14 sq.m.,  Plot Area]
418         [(681 sq.m.,  Built-up Area]
419           [(251 sq.m.,  Carpet Area]
420             [(301 sq.m.,  Plot Area]
421             [(151 sq.m.,  Plot Area]
422              [(33 sq.m.,  Plot Area]
423              [(18 sq.m.,  Plot Area]
424            [(75 sq.m.,  Carpet Area]
425              [(93 sq.m.,  Plot Area]
426           [(325 sq.m.,  Carpet Area]
427            [(23 sq.m.,  Carpet Area]
428             [(291 sq.m.,  Plot Area]
429              [(84 sq.m.,  Plot Area]
430              [(84 sq.m.,  Plot Area]
432             [(226 sq.m.,  Plot Area]
433             [(246 sq.m.,  Plot Area]
434             [(435 sq.m.,  Plot Area]
435              [(52 sq.m.,  Plot Area]
436             [(460 sq.m.,  Plot Area]
437              [(47 sq.m.,  Plot Area]
438              [(50 sq.m.,  Plot Area]
439               [(5 sq.m.,  Plot Area]
440              [(85 sq.m.,  Plot Area]
441            [(7692 sq.m.,  Plot Area]
442             [(226 sq.m.,  Plot Area]
443              [(33 sq.m.,  Plot Area]
444             [(124 sq.m.,  Plot Area]
445              [(84 sq.m.,  Plot Area]
446         [(132 sq.m.,  Built-up Area]
447            [(93 sq.m.,  Carpet Area]
448         [(301 sq.m.,  Built-up Area]
449              [(73 sq.m.,  Plot Area]
450              [(59 sq.m.,  Plot Area]
451             [(105 sq.m.,  Plot Area]
452               [(7 sq.m.,  Plot Area]
453         [(163 sq.m.,  Built-up Area]
454             [(184 sq.m.,  Plot Area]
455         [(105 sq.m.,  Built-up Area]
456              [(52 sq.m.,  Plot Area]
457             [(293 sq.m.,  Plot Area]
458              [(49 sq.m.,  Plot Area]
459              [(84 sq.m.,  Plot Area]
460             [(113 sq.m.,  Plot Area]
461         [(132 sq.m.,  Built-up Area]
462              [(84 sq.m.,  Plot Area]
463            [(84 sq.m.,  Carpet Area]
464             [(167 sq.m.,  Plot Area]
465             [(136 sq.m.,  Plot Area]
466              [(33 sq.m.,  Plot Area]
467             [(109 sq.m.,  Plot Area]
468            [(40 sq.m.,  Carpet Area]
469         [(483 sq.m.,  Built-up Area]
470              [(42 sq.m.,  Plot Area]
471              [(46 sq.m.,  Plot Area]
472              [(50 sq.m.,  Plot Area]
473           [(20064 sq.m.,  Plot Area]
474              [(56 sq.m.,  Plot Area]
475          [(15 sq.m.,  Built-up Area]
476              [(14 sq.m.,  Plot Area]
477              [(98 sq.m.,  Plot Area]
478         [(328 sq.m.,  Built-up Area]
479             [(336 sq.m.,  Plot Area]
480               [(5 sq.m.,  Plot Area]
481             [(167 sq.m.,  Plot Area]
482              [(84 sq.m.,  Plot Area]
483             [(560 sq.m.,  Plot Area]
484             [(110 sq.m.,  Plot Area]
485             [(167 sq.m.,  Plot Area]
486           [(151 sq.m.,  Carpet Area]
487              [(56 sq.m.,  Plot Area]
488              [(76 sq.m.,  Plot Area]
489              [(15 sq.m.,  Plot Area]
490              [(40 sq.m.,  Plot Area]
491            [(1115 sq.m.,  Plot Area]
492           [(234 sq.m.,  Carpet Area]

In [311]:
# skipping this col becoz it will lead to 2 new cols, so i'll do it after merge both flat and house datas.

# bedRoom

In [312]:
data['bedRoom'].str.split(' ').str[0].value_counts(dropna=False)

bedRoom
4      239
5      195
3      148
NaN    108
2       88
6       82
9       45
1       38
8       34
7       31
12      29
10      21
16      12
13       4
18       2
19       2
11       2
20       1
21       1
36       1
34       1
14       1
Name: count, dtype: int64

In [313]:
data['bedRoom'] = data['bedRoom'].str.split(' ').str[0]

# bathroom

In [314]:
data['bathroom'].str.split(' ').str[0].value_counts(dropna=False)

bathroom
4      233
3      166
5      139
2      114
NaN    108
6       85
1       65
9       42
7       39
8       29
12      23
10      11
16       8
13       4
18       4
11       4
20       3
17       3
14       2
21       1
36       1
34       1
Name: count, dtype: int64

In [315]:
data['bathroom'] = data['bathroom'].str.split(' ').str[0]

# balcony

In [316]:
data['balcony'].str.split(' ').str[0].str.replace('No', '0').value_counts(dropna=False)

balcony
3+     373
2      223
3      161
0      115
NaN    108
1      105
Name: count, dtype: int64

In [317]:
data['balcony'] = data['balcony'].str.split(' ').str[0].str.replace('No', '0')

In [318]:
data.sample(3)

,property_name,society,price_in_crores,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
648,1 Bedroom House for sale in Sushant Lok Phase 1,nan,2.15,13030,(153 sq.m.) Built-up Area,Built Up area: 1650 (153.29 sq.m.),1,1,0,NaN,"Block B, Sushant Lok I, Gurgaon, Sushant Lok P...",1 Floors,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...","Property for sale in sushant lok i, gurgaon. T...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
550,3 Bedroom House for sale in Gandhi Nagar,nan,1.45,8000,(167 sq.m.) Built-up Area,Built Up area: 1800 (167.23 sq.m.)Carpet area:...,3,2,1,NaN,68/179 Gali No 10 Gandhi Nagar Sector 11 Near ...,1 Floors,North,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'Ka...",3bhk residential house for sale. 68/179 gali n...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.7,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN

# additionalRoom

In [319]:
data['additionalRoom'].str.lower().fillna('not available').value_counts(dropna=False)

additionalRoom
not available                                    496
servant room                                      82
pooja room,study room,servant room,store room     63
others                                            59
pooja room                                        38
pooja room,study room,servant room                34
pooja room,study room,servant room,others         32
store room                                        31
pooja room,servant room                           24
study room,servant room                           19
study room                                        19
servant room,store room                           15
pooja room,store room                             11
pooja room,study room                             11
pooja room,others                                 11
pooja room,store room,study room,servant room      9
servant room,pooja room                            8
servant room,others                                8
study room,servant room,pooja room,store room      7
pooja room,servant room,store room                 7
servant room,pooja room,store room                 7
store room,servant room                            6
pooja room,servant room,others                     5
study room,pooja room,servant room                 5
servant room,store room,pooja room                 5
servant room,study room,pooja room,store room      5
servant room,study room                            5
store room,pooja room                              4
study room,servant room,store room                 4
pooja room,servant room,study room,store room      4
study room,servant room,store room,pooja room      4
pooja room,study room,others                       4
study room,others                                  3
study room,pooja room,servant room,store room      3
study room,servant room,pooja room                 3
pooja room,study room,store room                   3
study room,servant room,others                     2
study room,pooja room,store room,servant room      2
study room,pooja room                              2
store room,pooja room,servant room                 2
study room,pooja room,store room                   2
pooja room,study room,store room,servant room      2
store room,pooja room,study room                   2
store room,pooja room,study room,servant room      2
servant room,study room,store room,pooja room      2
servant room,study room,pooja room                 2
study room,store room                              1
store room,pooja room,servant room,study room      1
servant room,store room,study room,pooja room      1
study room,store room,pooja room                   1
store room,servant room,study room,pooja room      1
pooja room,store room,servant room                 1
servant room,others,pooja room                     1
study room,store room,servant room,pooja room      1
store room,study room,servant room                 1
store room,servant room,pooja room                 1
study room,others,servant room                     1
Name: count, dtype: int64

# noOfFloor

In [320]:
data['noOfFloor'].str.split(' ').str[0].value_counts(dropna=False)

noOfFloor
3      309
2      294
1      181
4      137
NaN    128
5        9
0        6
6        3
14       3
11       2
10       2
12       2
13       1
27       1
21       1
20       1
02       1
41       1
51       1
16       1
33       1
Name: count, dtype: int64

In [321]:
data['noOfFloor'] = data['noOfFloor'].str.split(' ').str[0]

In [322]:
data.sample(3)

,property_name,society,price_in_crores,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
509,7 Bedroom House for sale in Naharpur Rupa,nan,nan,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.),7,2,2,NaN,"Naharpur Rupa, Gurgaon, Haryana",2,South,10+ Year Old,"['Rajiv Chowk Mosque', 'Parmar Dental Clinic &...",Great location\n650meter from nh8\nNear by man...,NaN,['Water Storage'],"['Environment3 out of 5', 'Lifestyle3.5 out of..."
622,2 Bedroom House for sale in Sector 76 Gurgaon,suncity avenue 76,0.75,10067,(69 sq.m.) Plot Area,Plot area 745(69.21 sq.m.)Built Up area: 745 s...,2,2,2,NaN,"Sector 76 Gurgaon, Gurgaon, Haryana",11,North-East,Within 6 months,"['Omaxe Gurgaon Mall', 'Gurugram University', ...",500m from nh8\nClover leaf almost ready,NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ...",NaN
77,5 Bedroom House for sale in Sector 14 Gurgaon,nan,4.5,20000,(232 sq.m.) Carpet Area,Carpet area: 2500 (232.26 sq.m.),5,5,1,NaN,"Sector 14, Sector 14 Gurgaon, Gurgaon, Haryana",1,NaN,1 to 5 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",A residential house is available for sale. It ...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."

# facing

In [323]:
data['facing'].str.lower().str.strip().value_counts(dropna=False)

facing
NaN           412
east          181
north-east    159
north         113
west           75
north-west     44
south-east     40
south          36
south-west     25
Name: count, dtype: int64

In [324]:
data['facing'] = data['facing'].str.lower().str.strip().fillna('NA')

# agePossession

In [325]:
data['agePossession'].str.lower().value_counts(dropna=False)

agePossession
5 to 10 year old      256
1 to 5 year old       229
10+ year old          219
undefined             142
0 to 1 year old       111
NaN                   108
within 6 months         7
under construction      2
dec 2023                2
jun 2024                2
by 2027                 1
oct 2024                1
by 2024                 1
dec 2024                1
within 3 months         1
oct 2023                1
jan 2024                1
Name: count, dtype: int64

In [326]:
data['agePossession'] = data['agePossession'].str.lower()

# area_in_sqft

In [327]:
data['price_in_crores'] = data['price_in_crores'].astype('float')
data['price_per_sqft'] = data['price_per_sqft'].astype('float')

In [328]:
data.insert(loc=2, column='area_in_sqft', value=round((data['price_in_crores']*10000000)/data['price_per_sqft']))

# Finalizing

In [329]:
data.sample(3)

,property_name,society,area_in_sqft,price_in_crores,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1084,3 Bedroom House for sale in Sushant Lok Phase 3,nan,1650.0,4.75,28787.0,(149 sq.m.) Plot Area,Plot area 1600(148.64 sq.m.)Built Up area: 170...,3,3,3,Store Room,240 Sq.Yrd Old Siplex 3 Bhk Villa In Gated Blo...,2,north-west,5 to 10 year old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",240 sq.Yrd park facing simplex 3 bhk villa for...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '11 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
714,3 Bedroom House for sale in Sector 82 Gurgaon,vatika signature villas,2230.0,3.20,14351.0,(201 sq.m.) Plot Area,Plot area 2160(200.67 sq.m.),3,4,3,"Pooja Room,Study Room,Servant Room,Store Room","Sector 82 Gurgaon, Gurgaon, Haryana",1,NA,0 to 1 year old,"['IFFCO Chowk Flyover', 'Vega Schools', 'IGIA']","240sq yard simplex villa near post office, nh ...","['6 Light', '4 AC', '1 Modular Kitchen', 'No B...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
853,5 Bedroom House for sale in Nirvana Country,unitech espace,3240.0,11.29,34846.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5,5,3+,"Study Room,Pooja Room","Nirvana Country, Gurgaon, Haryana",2,NA,5 to 10 year old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Urgent for sale villa\nConfirm deal\nNice loca...,"['7 Fan', '8 Light', '4 AC', 'No Bed', 'No Chi...","['Maintenance Staff', 'Water Storage', 'Fitnes...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [330]:
data['property_type'] = 'house'

In [331]:
data['floorNum'] = '0'

In [332]:
data.shape

(1085, 22)

In [333]:
data.columns

Index(['property_name', 'society', 'area_in_sqft', 'price_in_crores',
       'price_per_sqft', 'area', 'areaWithType', 'bedRoom', 'bathroom',
       'balcony', 'additionalRoom', 'address', 'noOfFloor', 'facing',
       'agePossession', 'nearbyLocations', 'description', 'furnishDetails',
       'features', 'rating', 'property_type', 'floorNum'],
      dtype='object')

In [334]:
data.to_csv(r'F:\Github_dsc\HousePrice_MegaProject\2. data_cleaning\0. data\cleaned_houses_data.csv')