In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

flats_data = pd.read_csv(r'F:\Github_dsc\HousePrice_MegaProject\2. data_cleaning\0. data\cleaned_flats_data.csv')
houses_data = pd.read_csv(r'F:\Github_dsc\HousePrice_MegaProject\2. data_cleaning\0. data\cleaned_houses_data.csv')

In [2]:
data = pd.concat([flats_data, houses_data], ignore_index=True)

In [3]:
data = data.sample(data.shape[0], ignore_index=True)

In [4]:
data.sample(3)

,Unnamed: 0,property_name,society,area_in_sqft,price_in_crores,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,noOfFloor,area
3793,1065,4 Bedroom House for sale in Nirvana Country,unitech espace,2160.0,7.42,34351.0,Plot area 2160(200.67 sq.m.)Built Up area: 320...,4.0,4.0,3,NaN,"Good Location Villa On Sale, Nirvana Country, ...",0.0,west,10+ year old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...","4bhk independent villa on sale, espace, nirvan...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ...",house,2.0,(201 sq.m.) Plot Area
2041,1956,3 BHK Flat in Sector 77 Gurgaon,emaar palm heights,2000.0,2.25,11250.0,Super Built up area 2000(185.81 sq.m.),3.0,3.0,3,servant room,"Sector 77 Gurgaon, Gurgaon, Haryana",22.0,NaN,0 to 1 Year Old,"['DLF Cyber City', 'Vatika Town Square', ""St. ...","Unused,with covered parking,vaastu compatible","['1 Geyser', '1 Stove', '1 Chimney', '5 AC', '...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment5 out of 5', 'Lifestyle4 out of 5...",flat,1.0,NaN
472,2116,2 BHK Flat in Sector 68 Gurgaon,m3m sierra 68,1220.0,1.25,10245.0,Super Built up area 1220(113.34 sq.m.)Carpet a...,2.0,2.0,3,not available,"Sector 68 Gurgaon, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Airia Mall', 'Sohna Road', 'Golf Course Exte...","2 bhk flat in posh society\nGated, secure and ...","['4 Fan', '1 Exhaust Fan', '9 Light', '4 Wardr...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5...",flat,1.0,NaN

In [5]:
data.drop(columns=['Unnamed: 0'], axis=1, inplace=True)

In [6]:
data.sample(3)

,property_name,society,area_in_sqft,price_in_crores,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,noOfFloor,area
2778,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,2250.0,8.70,38667.0,Plot area 250(209.03 sq.m.)Built Up area: 267 ...,4.0,5.0,2,"Study Room,Servant Room","Sector 66 Gurgaon, Gurgaon, Haryana",0.0,east,0 to 1 year old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Looking to buy an independent house in gurgaon...,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Environment3 out of 5', 'Lifestyle4 out of 5...",house,3.0,(209 sq.m.) Plot Area
3413,2 BHK Flat in Ashok Vihar Phase 3 Extension,pooja apartment,700.0,0.25,3571.0,Carpet area: 700 (65.03 sq.m.),2.0,2.0,2,not available,"Flat No 201, Ashok Vihar Phase 3 Extension, Gu...",2.0,east,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",2nd floor with car parking at ground level. In...,"['2 Fan', '2 Geyser', '6 Light', '1 Chimney', ...",NaN,"['Environment3 out of 5', 'Safety4 out of 5', ...",flat,1.0,NaN
1164,2 BHK Flat in Sector 2 Gurgaon,mittal cosmos executive apartments,1145.0,0.75,6550.0,Super Built up area 1145(106.37 sq.m.)Built Up...,2.0,2.0,2,not available,"Sector 2 Gurgaon, Gurgaon, Haryana",15.0,NaN,10+ Year Old,"['Global Foyer Mall', 'Dwarka Expressway', 'Th...",We are the proud owners of this 2 bhk apartmen...,"['2 Wardrobe', '1 Water Purifier', '3 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Management4.5 out of 5', 'Green Area5 out of...",flat,1.0,NaN

In [7]:
data.shape

(4082, 22)

In [8]:
data.to_csv(r'F:\Github_dsc\HousePrice_MegaProject\2. data_cleaning\0. data\merged_flat_house_data.csv')